# Generated by Django 2.0 on 2018-01-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180101_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to='profile/'),
        ),
    ]
