# Generated by Django 2.0 on 2018-01-04 15:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180103_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
