# Generated by Django 2.0 on 2018-01-05 08:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300, unique=True)),
                ('url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('gameimage', models.ImageField(blank=True, null=True, upload_to=game.models.user_directory_path)),
                ('viewcount', models.PositiveIntegerField(default=0)),
                ('sellcount', models.PositiveIntegerField(default=0)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['viewcount', 'sellcount'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameScore', models.IntegerField()),
                ('gameState', models.TextField(default="{''}")),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selldate', models.DateTimeField(auto_now_add=True)),
                ('game_played', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.GamePlayed')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameplayed',
            name='users',
            field=models.ManyToManyField(through='game.PaymentDetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
