# Generated by Django 2.0 on 2017-12-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
