# Generated by Django 2.0 on 2017-12-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameplayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayed',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='game',
            name='gameimage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(),
        ),
    ]
