# Generated by Django 2.0 on 2017-12-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171228_1855'),
        ('game', '0003_auto_20171229_1011'),
    ]

    operations = [
    ]
