# Generated by Django 2.0 on 2017-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20171230_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
