# Generated by Django 2.0 on 2017-12-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20171230_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(max_length=300, unique=True),
        ),
    ]
