# Generated by Django 2.0 on 2018-01-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20171230_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameimage',
            field=models.ImageField(blank=True, null=True, upload_to='game/'),
        ),
    ]
