# Generated by Django 2.0 on 2018-01-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20180103_1250'),
        ('game', '0010_auto_20180101_2056'),
    ]

    operations = [
    ]
