# Generated by Django 2.0 on 2018-01-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_game_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayed',
            name='game',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='game.Game'),
            preserve_default=False,
        ),
    ]
