# Generated by Django 2.0 on 2018-01-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20180104_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayed',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Game'),
        ),
    ]
