# Generated by Django 2.0 on 2018-01-04 15:40

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20180104_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameimage',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.user_directory_path),
        ),
    ]
