# Generated by Django 2.0 on 2018-01-06 19:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0018_auto_20180104_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selldate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['viewcount', 'sellcount']},
        ),
        migrations.AddField(
            model_name='game',
            name='sellcount',
            field=models.PositiveIntegerField(default=0),
        ),
        
	migrations.RemoveField(
	    model_name='gameplayed',
	    name='users',
	),
	migrations.AddField(
	    model_name='gameplayed',
	    name='users',
	    field=models.ManyToManyField(through='game.PaymentDetail', to=settings.AUTH_USER_MODEL),
	),
        migrations.AddField(
            model_name='paymentdetail',
            name='game_played',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.GamePlayed'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
