# Generated by Django 2.0 on 2018-01-07 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20180106_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='upload_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
