# Generated by Django 2.0 on 2018-01-07 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_game_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
