# Generated by Django 2.0 on 2018-01-07 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20180107_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
