# Generated by Django 2.0 on 2018-01-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20180107_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayed',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
