# Generated by Django 2.0 on 2018-01-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_game_gamethumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamethumb',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
