# Generated by Django 2.0 on 2018-01-18 15:17

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20180118_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamethumb',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.user_directory_path),
        ),
    ]
