# Generated by Django 2.0 on 2018-01-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20180119_1403'),
        ('game', '0025_auto_20180112_1731'),
    ]

    operations = [
    ]
