# Generated by Django 2.0 on 2018-01-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_merge_20180124_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
