# Generated by Django 2.0 on 2018-01-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_auto_20180124_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
    ]
