# Generated by Django 2.0 on 2018-02-07 14:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_game_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
