# Generated by Django 2.0 on 2018-02-05 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0032_auto_20180205_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayed',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='gameplayed',
            unique_together={('game', 'user')},
        ),
    ]
