# Generated by Django 2.0 on 2018-02-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_game_revenue'),
        ('game', '0033_auto_20180205_0814'),
    ]

    operations = [
    ]
